### ISSUE TITLE
Incorrect data on poolShares

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#12]
I can't find all the pool shares.
For example in [this query](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20PoolsQuery%20%7B%0A%20%20%20%20poolShares(orderDirection%3Adesc%2C%20where%3A%7BuserAddress%3A%220xe08a1dae983bc701d05e492db80e0144f8f4b909%22%7D)%20%7B%0A%20%20%20%20%20%20%20id%0A%20%20%20%20%09%20balance%0A%20%20%20%20%09%20userAddress%20%7B%0A%20%20%20%20%09%20%20%20id%0A%20%20%20%20%09%20%7D%0A%20%20%20%20%09%20poolId%20%7B%0A%20%20%20%20%09%20%20%20id%0A%20%20%20%20%09%20%7D%0A%20%20%20%20%7D%0A%20%20%7D&operationName=PoolsQuery) i can't find my shares from the pool 0x4c55D2944BE2914611B950Fbfd408b21062bf8d8

![image](https://user-images.githubusercontent.com/26000280/106024126-20854100-60d0-11eb-8952-a586cbbc6404.png)

**Comment by ssallam** [comment]
This is now fixed, it seems that the rinkeby subgraph node stopped processing events.

**Comment by mihaisc** [comment]
Looks ok
