### ISSUE TITLE
pool shares can't be ordered by actual lockedValue

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean-subgraph#14]
Ordering by count of pool shares is possible but that's kinda not useful cause 1 pool share can be worth $1, or $1000000. What we need is ordering pool shares by that `poolId.lockedValue`

Example:
In [this query](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolShares(orderBy%3Abalance%2CorderDirection%3A%20desc%2C%20first%3A%201000%2C%20where%3A%20%7BuserAddress%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20balance%0A%20%20%20%20userAddress%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20poolId%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20datatokenReserve%0A%20%20%20%20%20%20oceanReserve%0A%20%20%20%20%20%20lockedValue%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20tokenId%20%7B%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) ordering by pool share count (`balance`) is possible but no way to order by the actual value

**Comment by mihaisc** [comment]
This can't be done in the graph. Each time someone adds/removes tokens from a pool, it's value changes, so the value of 1 share changes as well. So basically on any event you need to update all the `PoolShare` items related to that pool. 
We can't really have anything that is dynamic  like how many ocean/dt you have in a pool, the actual price of the shares that you own, etc..
Looking at uniswap they have a similar usage : they fetch everything from the graph , get want else they need from chain and sort/paginate on client side.
