### ISSUE TITLE
lockedValue based on pool share

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean-subgraph#15]
In a [query like this](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolShares(orderBy%3A%20balance%2C%20orderDirection%3A%20desc%2C%20where%3A%20%7BuserAddress%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%7D%2C%20first%3A%201000)%20%7B%0A%20%20%20%20balance%0A%20%20%20%20poolId%20%7B%0A%20%20%20%20%20%20datatokenAddress%0A%20%20%20%20%20%20lockedValue%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), `poolShares.poolId.lockedValue` returns the total locked value of the pool

### Expected

When using `poolId` within a filtered `poolShares` query, `lockedValue` should reflect the user's locked value based on their pool share

**Comment by mihaisc** [comment]
This might be too complicate and imply customizing the graph, an easier solution i  thing would be to add to `PoolShare` : `lockedValue`, `oceanTokenAmount , `datatokenAmount`

**Comment by mihaisc** [comment]
Unfortunately same answer as in https://github.com/oceanprotocol/ocean-subgraph/issues/14
