### ISSUE TITLE
Implement pool snapshot

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#180]
Will be usefull in graphs/statistics

Probable schema.
```
type PoolSnapshot @entity {
  id: ID!
  pool: Pool!
  totalShares: BigDecimal!
  swapVolume: BigDecimal!                                             # swap value 24h
  swapFees: BigDecimal!                                               # swap fee value 24h  
  timestamp: Int!                                                     # date without time
  spotPrice: BigDecimal!                                              # TODO: last spot price or first one?
  tokens: [PoolSnapshotTokenValue!] @derivedFrom(field: "poolSnapshot")
}
```

**Comment by trentmc** [comment]
We're not using Bal v2 in the first release of Ocean V4. 

Therefore: is this issue still relevant, or should we close?

**Comment by mihaisc** [comment]
It is, it's not related to to balancer v2 pools , it's related to the subgraph implementation of balancer v2 (this is where i got my inspiration). Changed the title so it's not  confusing. Already have a working draft working for it. Don't want to implement it in v3 because it won't be of much value without other changes in the market and at this we want to freeze the market.

**Comment by trentmc** [comment]
thx for the clarification! :)

**Comment by mihaisc** [comment]
deprecated by https://github.com/oceanprotocol/ocean-subgraph/issues/208
