### ISSUE TITLE
subgraph only indexes non-checksummed addresses 

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/ocean-subgraph#196]
EIP-55 checksum address: 0x02088F1E1D088a8D1D5D888c34b2fD3073d950C1

```js
// lower case address
"0x02088F1E1D088a8D1D5D888c34b2fD3073d950C1".toLowerCase()
"0x02088f1e1d088a8d1d5d888c34b2fd3073d950c1"
``` 

checksum address: https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pools(where%3A%20%7B%20datatokenAddress%3A%20%220x02088F1E1D088a8D1D5D888c34b2fD3073d950C1%22%7D)%20%7B%0A%20%20%20%20id%2C%0A%20%20%7D%0A%7D%0A
lowercase address: https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pools(where%3A%20%7B%20datatokenAddress%3A%20%220x02088f1e1d088a8d1d5d888c34b2fd3073d950c1%22%7D)%20%7B%0A%20%20%20%20id%2C%0A%20%20%7D%0A%7D%0A

https://web3-tools.netlify.app/ tool to validate checksummed addresses

My expectation as a user is that subgraph indexes checksum addresses or allows all two variations (checksum, lowercase).

**Comment by mihaisc** [comment]
Hi Tim, unfortunately this is how TheGraph works.

**Comment by alexcos20** [comment]
Unfortunately, this is how the graph works.  Everything in lowercase :(

**Comment by TimDaub** [comment]
:( ok then this can be closed. Would it make sense to file an issue upstream?
