### ISSUE TITLE
subgraph can't find pool for NEFTUR-75

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/ocean-subgraph#197]
1. query https://aquarius.mainnet.oceanprotocol.com/api/v1/aquarius/assets/ddo and check NEFTUR-75  https://market.oceanprotocol.com/asset/did:op:6ef1ccD8423f2C1D87532Ef69C156f710eCC4f6e, in its response, it has 1 pool 0xA802aBffB5Ea1C09f18930B82a45A16B5CA8F89e
2. convert `datatokenAddress` to lower case 0x6ef1ccd8423f2c1d87532ef69c156f710ecc4f6e
3. make query to subgraph for pools: https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pools(where%3A%20%7B%20datatokenAddress%3A%20%220x6ef1ccd8423f2c1d87532ef69c156f710ecc4f6e%22%7D)%20%7B%0A%20%20%20%20id%2C%0A%20%20%7D%0A%7D%0A
4. subgraph doesn't find pool

it's not in list-purgatory either: https://github.com/oceanprotocol/list-purgatory/search?q=did%3Aop%3A6ef1ccD8423f2C1D87532Ef69C156f710eCC4f6e

**Comment by mihaisc** [comment]
Because there is no pool created . You can find the datatoken

https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20datatoken(id%3A%220x6ef1ccd8423f2c1d87532ef69c156f710ecc4f6e%22)%20%7B%0A%20%20id%2C%0A%20%20symbol%0A%7D%0A%7D%0A

**Comment by TimDaub** [comment]
isn't this its pool? https://etherscan.io/address/0xA802aBffB5Ea1C09f18930B82a45A16B5CA8F89e#readContract

<img width="1174" alt="Screen Shot 2021-08-09 at 13 14 53" src="https://user-images.githubusercontent.com/2758453/128698175-d713a900-4c09-433a-be56-2304527a704b.png">

[base token is bdp](https://etherscan.io/address/0xf3dcbc6d72a4e1892f7917b7c43b74131df8480e)

**Comment by alexcos20** [comment]
Hey.
For now, our subgraphs are indexing only pools DT/OceanToken.

That pool contains DT/BDP.

**Comment by TimDaub** [comment]
> For now, our subgraphs are indexing only pools DT/OceanToken.

makes sense. And as I understand, it may be indexed by Aquarius if it's not set as encrypted in the DDO?
To me that's OK. But then I think you should consider having one directive for both Aquarius and subgraph.

Because from what I understand this circumstance leads to an error in the OCEAN UI right now: https://market.oceanprotocol.com/asset/did:op:6ef1ccD8423f2C1D87532Ef69C156f710eCC4f6e

It's shown as ocean data set but without a pool.
