### ISSUE TITLE
pool token in not being added for swaps

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#213]
For some reason on swap events only pool token out is being added to tx.

**Comment by kremalicious** [comment]
Consider [this query](https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20TransactionHistory%20%7B%0A%20%20%20%20poolTransactions(%0A%20%20%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20%20%20where%3A%20%7B%20userAddress%3A%20%220x655efe6eb2021b8cefe22794d90293aec37bb325%22%20%7D%0A%20%20%20%20%20%20first%3A%201000%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20poolToken%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20tokenAddress%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20tx%0A%20%20%20%20%20%20event%0A%20%20%20%20%20%20timestamp%0A%20%20%20%20%20%20poolAddress%20%7B%0A%20%20%20%20%20%20%20%20datatokenAddress%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A&operationName=TransactionHistory).

which produces this for a swap tx:

```json
{
  "event": "swap",
  "poolAddress": {
    "datatokenAddress": "0x7bce67697ed2858d0683c631dde7af823b7eea38"
  },
  "timestamp": 1623831918,
  "tokens": [
    {
      "poolToken": {
        "id": "0xaab9eaba1aa2653c1dda9846334700b9f5e14e44-0x7bce67697ed2858d0683c631dde7af823b7eea38",
        "symbol": "QUICRA-0"
      },
      "tokenAddress": "0x7bce67697ed2858d0683c631dde7af823b7eea38",
      "type": "out",
      "value": "-18.999999999825224137"
    }
  ],
  "tx": "0x2a64a94bba6b9542885fec11467a161bde3583eefcfecbf11e5add390b11a9bf"
},
```

Notice how `tokens[]` only holds 1 `type: out` token info, but for swap tx we need `type: in` & `type: out`
