### ISSUE TITLE
Edit information related to datatoken

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/ocean-subgraph#28]
We have the following situation on the market [#282](https://github.com/oceanprotocol/market/issues/282) , related to the sub-graph: 
- for a data token, we can fetch the `address`, `tx` and `createTime`
- we do not have the  `editTimestamps` related to each data token

Would it be possible to have a list of `editTimestamps` related to each data token? 
I think that would be useful in resolving this task.

**Comment by ssallam** [comment]
see pr #47 for solution details
