### ISSUE TITLE
pool `id` filter vs. poolSnapshots `pool` filter

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean-subgraph#301]
Might be simple change, or not possible at all and hard to explain. Consider [this combined query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolSnapshots(first%3A%201000%2C%20where%3A%20%7Bpool%3A%20%220xd231f99f8f9f6dccfd04c504155c13551ef71e2e%22%7D%2C%20orderBy%3A%20date)%20%7B%0A%20%20%20%20date%0A%20%20%20%20spotPrice%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20swapVolume%0A%20%20%20%20totalShares%0A%20%20%7D%0A%20%20pool(id%3A%20%220xd231f99f8f9f6dccfd04c504155c13551ef71e2e%22)%20%7B%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20poolShares(where%3A%20%7Buser%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%2C%20shares_gt%3A%200.001%7D%2C%20first%3A%201000)%20%7B%0A%20%20%20%20shares%0A%20%20%7D%0A%7D%0A).

All works but generating typings from that will fail as `pool` filter in `poolSnapshots` is defined as `String`, but `id` filter in `pool` as `ID` which prevents us from using more combined queries where we pass the pool address:

<img width="438" alt="Screen Shot 2022-01-25 at 16 11 46" src="https://user-images.githubusercontent.com/90316/151014651-a402e368-34f5-471c-8487-b52302b55fa3.png">

So what would help in this case is that whenever we assume a pool address is passed, the type for it should always be the same, so in this case `pool` filter in `poolSnapshots` should be `ID`. Although unsure if GraphQL requires only one `ID` per node being defined or something. Or everything with an address being passed should be `String`

**Comment by mihaisc** [comment]
i get the issue unfortunately this will not work pool is of type `Pool!` and the filter is auto generated by the graph. I'll try to think of an alternative

**Comment by kremalicious** [comment]
cool, thanks, not sure yet this would be sufficient with my mega pool query but I'll try. This is now the one I need to make work:
https://github.com/oceanprotocol/market/blob/77cd001f9ddd5578e6120f4db563c16953d9ba2f/src/%40utils/subgraph.ts#L285-L325

**Comment by mihaisc** [comment]
Well the easy fix would be to just have two variables `poolId: ID` and `poolIdAsString: String` in the query and then in market you just pass the same value to both. I get that it's not the best but honestly it's way better to have multiple queries coupled like this , less http calls, less code complexity ,etc.

**Comment by kremalicious** [comment]
Should have posted [new actual query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20PoolData(%24pool%3A%20String!%2C%20%24owner%3A%20String!%2C%20%24user%3A%20String)%20%7B%0A%20%20poolData%3A%20pool(id%3A%20%24pool)%20%7B%0A%20%20%20%20id%0A%20%20%20%20totalShares%0A%20%20%20%20poolFee%0A%20%20%20%20opfFee%0A%20%20%20%20marketFee%0A%20%20%20%20spotPrice%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenWeight%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%7D%0A%20%20%20%20datatokenWeight%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%24owner%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20poolDataUser%3A%20pool(id%3A%20%24pool)%20%7B%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%24user%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20poolSnapshots(first%3A%201000%2C%20where%3A%20%7Bpool%3A%20%24pool%7D%2C%20orderBy%3A%20date)%20%7B%0A%20%20%20%20date%0A%20%20%20%20spotPrice%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20swapVolume%0A%20%20%7D%0A%7D%0A&operationName=PoolData&variables=%7B%0A%20%20%22pool%22%3A%20%220xd231f99f8f9f6dccfd04c504155c13551ef71e2e%22%2C%0A%20%20%22user%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%2C%0A%20%20%22owner%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%0A%7D) from https://github.com/oceanprotocol/market/pull/1020

But looks like we just deployed a new Rinkeby subgraph? My pool on my test asset is suddenly gone

**Comment by mihaisc** [comment]
yep, fun times

**Comment by kremalicious** [comment]
got the workaround going on another test asset in https://github.com/oceanprotocol/market/pull/1020, so closing this here, thanks for the help!
