### ISSUE TITLE
`poolSnapshots` returns only 1 data point

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean-subgraph#305]
[This query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query(%24pool%3A%20String!)%7B%0A%20%20poolSnapshots(first%3A%201000%2C%20where%3A%20%7Bpool%3A%20%24pool%7D%2C%20orderBy%3A%20date)%20%7B%0A%20%20%20%20date%0A%20%20%20%20spotPrice%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20swapVolume%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22pool%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22poolAsString%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22user%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%2C%0A%20%20%22owner%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%0A%7D) should return multiple data points as I added liquidity multiple times, but it's returning only last data point.

**Comment by mihaisc** [comment]
Not a bug, all the tx were done in the same day ( [query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0AfixedRateExchanges%7B%0A%20%20datatoken%20%7B%0A%20%20%20%20id%0A%20%20%20%20symbol%0A%20%20%7D%0A%20%20id%0A%7D%0A%7D) ) . The pool snapshot is per day.  It represents the total at the end of the day

**Comment by kremalicious** [comment]
ha, that like makes total sense, was so used to our live behavior
