### ISSUE TITLE
Calculate liquidity for each pool

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-subgraph#4]
Liquidity is expressed in Ocean.
Total Value Locked  = total value locked in all pools  (GUI)

Related to:  https://github.com/oceanprotocol/market/pull/311#issuecomment-758425502

(see how balancer is using namings in graph schema)

Implementation details
poolfactory has totalLockedValue (in OCEAN)
pool has lockedValue (in OCEAN)
on each pool update:
```
  oldValue = pool.lockedValue
  pool.lockedValue = oceanReserve + dtReserve * spotPrice
  totalLockedValue = totalLockedValue + pool.lockedValue - oldValue
```

**Comment by ssallam** [comment]
This is completed and deployed to the test node.
