### ISSUE TITLE
Change type of `lastPriceToken` from string to Token

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#447]
On Order , `lastPriceToken` should be `Token`

**Comment by jamiehewitt15** [comment]
I changed it back to string as it was causing problems: https://github.com/oceanprotocol/ocean-subgraph/pull/477

Will do another PR for this with more testing.

**Comment by mihaisc** [comment]
we need to make sure the Token exists, so when assigning a value to `lastPriceToken` we need to do a  `getToken`. This function automatically created the token if not existing.

**Comment by mihaisc** [comment]
That should be it. Then we need to debug what is not working.
