### ISSUE TITLE
ProviderFees

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-subgraph#471]
Add providerFees to orders (equivalent of startOrder) and reuse orders

**Comment by mihaisc** [comment]
It will be stored as a simple string. The client will convert to json as needed

**Comment by AnaLoznianu** [comment]
@bogdanfazakas Are the provider fees integrated on market/ocean.js?

**Comment by soonhuat** [comment]
@mihaisc wonder if providerFee will be part of Order entity or also part of OrderReuse entity?

**Comment by jamiehewitt15** [comment]
> It will be stored as a simple string. The client will convert to json as needed

Within OPC, providerFee is stored as `BigDecimal` - are you sure you don't want it to be the same?

**Comment by soonhuat** [comment]
@jamiehewitt15 if I were right, the providerFee actually is not the cost in numeric, is the whole **ProviderFee object** index as string
https://github.com/oceanprotocol/contracts/blob/e3d75c901aa66c8cfc1ac69b1a339d1356a9f383/contracts/templates/ERC20TemplateEnterprise.sol#L68

**Comment by jamiehewitt15** [comment]
> @jamiehewitt15 if I were right, the providerFee actually is not the cost in numeric, is the whole **ProviderFee object** index as string 

Yeah, that's true 👍

**Comment by alexcos20** [comment]
We need to store all values from providerFee event: https://github.com/oceanprotocol/contracts/blob/v4main/contracts/templates/ERC20Template.sol#L133-L142
