### ISSUE TITLE
DID

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-subgraph#472]
Since we have the nft address in the subgraph, by computing sha256(nftAddress+chainID) we could store the DID of the asset in the subgraph.

Maybe it's going to be helpful

**Comment by mihaisc** [comment]
true, it's an easy add

**Comment by alexcos20** [comment]
closing this, because we don't have sha256 support :)
https://thegraph.com/docs/en/developer/assemblyscript-api/#crypto-api
