### ISSUE TITLE
Subgraph miss some datas

### ISSUE THREAD

**Issue by astrid-net** [oceanprotocol/ocean-subgraph#483]
I'm trying to fetch data from this dataset: https://market.oceanprotocol.com/asset/did:op:d304cd36c780ae25c9732ca03c1209fe3655e3663fcd79ce05dc6e54984ebb53

So I used a query with PoolSnapShot that returns some data (liquidity, spot price) exactly at the block of first transaction of the contract (seeing the contract address first transaction, it was done at block 30257674) But when I try to fetch all pool ID I don't find that one that interests me. 

This is the query I use:
```
{poolSnapshots(orderBy: baseTokenLiquidity, orderDirection: desc, block: {number:30257674})
  {
    id
    baseTokenLiquidity
    datatokenLiquidity
    spotPrice}
}
```
And I should find the dataset linked above, which pool address is 0x800d0c1e4fb219a2d9bd2f292aa91abdcd862915.
This is a bug I guess.

**Comment by mihaisc** [comment]
Is [this](https://v4.subgraph.polygon.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0ApoolSnapshots(where%3A%7Bpool%3A%220x800d0c1e4fb219a2d9bd2f292aa91abdcd862915%22%7D)%7B%0A%20%0A%20%20%20%20id%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20spotPrice%0A%7D%0A%7D) what you are looking for?

**Comment by astrid-net** [comment]
I solve the problem with the query you shared. Thank you.

**Comment by mihaisc** [comment]
You're welcome

**Comment by astrid-net** [comment]
@mihaisc sorry, I'm trying to execute a Post request with Python. This is the code:

```
address = "0x800d0c1e4fb219a2d9bd2f292aa91abdcd862915"
data= """{"query":"{poolSnapshots(where:{pool:"%s"}, orderBy: date){id baseTokenLiquidity datatokenLiquidity spotPrice}}","variables":null,"operationName":null}"""%(address)
response = requests.post('https://v4.subgraph.polygon.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph', data=data).json()

```
But I got the following error:
`GraphQL server error (client error): expected `,` or `}` at line 1 column 39: 0`

It looks like the server doesn't accept the double quotes. Do you know why? Thanks.

**Comment by mihaisc** [comment]
try to use escape characters like `where:{pool:\"%s\"}` and if that doesn't work try to use variables

**Comment by astrid-net** [comment]
I already tried but it won’t work. Could you show me how to use variables, please? Idk. Thank you.
