### ISSUE TITLE
Remove AMM pools functionality

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean-subgraph#491]
As we are moving away from the dynamic pricing schema, we need to remove everything POOL related.
- [ ] Remove POOL related code
- [ ] Update READMEs

**Comment by mihaisc** [comment]
Yes that's a good point, but not sure how long we will be interested in this.
Cons:
- having old/redundant code is not awesome (not high impact )
- higher price, rpc calls cost :)

**Comment by jamiehewitt15** [comment]
This is closed by https://github.com/oceanprotocol/ocean-subgraph/pull/493 and https://github.com/oceanprotocol/ocean-subgraph/pull/492
