### ISSUE TITLE
Track updates and swaps in FixedRateExchange

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/ocean-subgraph#509]
Neither `updates` or `swaps` are tracked in `FixedRateExchange`

**Comment by mihaisc** [comment]
what do you mean ? [example](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql)

**Comment by jamiehewitt15** [comment]
Yeah seems to be working. Always seems to be null in the tests but I'll look into that more
