### ISSUE TITLE
Sales graph

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean-subgraph#547]
Blocks: [#1075](https://github.com/oceanprotocol/market/issues/1705)

For the sales graph we want to integrate into the market, we will need the data to be computed inside the subgraph. 
We should display the sales information per
- [ ] week
- [ ] month
- [ ] year
- [ ] all

**Comment by trentmc** [comment]
This has been built via other work. Alex's stats work, and (external) autobots
