### ISSUE TITLE
NFT Transfer event and related entity not persisted in subgraph and not queryable

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/ocean-subgraph#570]
**Is your feature request related to a problem? Please describe.**
NFT Transfer event are not queryable from GraphQL queries.
token, order or other entities unable to access history of previous/pass owner.

**Describe the solution you'd like**
Subgraph to index transfer event for existing assets.
Token entity to have list of previous/pass owner.

**Additional context**
So that we able to:
1. Trace the pass owner after very long time, maybe 1 year in the pass.
2. Consolidate the orders and number of orders under specific owner of specific duration for specific asset (through multiple query if needed to).

@jamiehewitt15 this is the topic we talk about last week (week 45, 2022)

**Comment by soonhuat** [comment]
According to Alex, would be beneficial and easier to access if `nft owner` are added to `order` entity on top of above suggestion

**Comment by alexcos20** [comment]
We have to do :
1. for [Order](https://github.com/oceanprotocol/ocean-subgraph/blob/main/schema.graphql#L142) entity, add  new field called owner, of type user
2. Add new entity NftTransferHistory, which contains:
- id:  hash(nftAddress+txId+eventNumber)
- oldOwner:  User!
- newOwner: User!
- txId: string
- timestamp:  Bigint!
- block: Int!
3. Change [Nft](https://github.com/oceanprotocol/ocean-subgraph/blob/main/schema.graphql#L71) entity:
 - make owner as User!  (it's string now)
 - make creator as User!  (it's string now)
 - add transferHistory: NftTransferHistory

**Comment by jamiehewitt15** [comment]
Do we also want `nftOwner` on `OrderReuse`?

**Comment by soonhuat** [comment]
For the use case perspective, nftOwner is not required because OrderReuse only involve provider fee (compute env).
And reuseOrder entity has order entity in it.
