### ISSUE TITLE
Add consumeMarket to orders

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-subgraph#621]
For some reason, it's commented in the code:  https://github.com/oceanprotocol/ocean-subgraph/blob/main/src/mappings/erc20Templates.ts#L62-L63

**Comment by mariacarmina** [comment]
It's the same problem that happened on PR #630, see [this comment ](https://github.com/oceanprotocol/ocean-subgraph/pull/630#issuecomment-1481410153). The handler for order started contains `OrderStarted` event which does not include consume market fees info, that's a separate event. I suggest to create separate objects for fees and use them wherever needed.
