### ISSUE TITLE
Fix ve delegation calculations

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/ocean-subgraph#622]
Subgraph records the delegated veOCEAN amount. We should be recording the percentage delegated instead.
Ticket reopened until everything is deployed and running in mainnet

```
curVeOcean = getVeOceanBalance(_delegator)
pctDelegated = _amount / curVeOcean
```

Order of blockers:
1. Subgraph mainnet is not deployed because goerli isn't quite signed off.
2. Norbert is stuck because subgraph mainnet is not deployed.

#DoD:
- [x] Subgraph goerli has the veDelegate and the right schema (https://v4.subgraph.goerli.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql)

**Comment by idiom-bytes** [comment]
@jamiehewitt15 this isn't quite done, we need to ship it in production
