### ISSUE TITLE
Publishing a dataset with USDC 6 decimal `publisherMarketFeeToken` have wrong `publishMarketFeeAmount` stored in subgraph

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/ocean-subgraph#664]
**Describe the bug**
Hi there I am trying to publish an asset with `publisherMarketOrderFee` of  `'1'` using `USDC` as the `publisherMarketFeeToken`. After publishing, I realised that the outcome value for `publishMarketFeeAmount` stored in subgraph is wrong. Hence, the dataset cannot be consumed by anyone.

**To Reproduce**
1. Start a localhost marketplace  
2. Go to `app.config.js`, update `publisherMarketOrderFee = '1'`
3. Go to `src/components/Publish/_utils.ts`, look for `const ercParams` and update the `feeToken: '0x07865c6E87B9F70255377e024ace6630C1Eaa37F'` (6 decimal USDC Address)
4. Start the marketplace in localhost, and publish a fixed price asset
5. Go to the [published dataset page](https://github.com/oceanprotocol/market/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=)
6. Open Network tab in developer tool (right-click inspect element), look for subgraph response
7. check the `publishMarketFeeAmount` as in the screenshot

**Expected behavior**
1. `publishMarketFeeAmount` should be `1` for dataset published using `USDC` as the `publisherMarketFeeToken`

**Screenshots**
As in the screenshot below, we can observe that `publisherMarketFeeAmount` is equal to `1000000000000` for the response from subgraph.
![image](https://user-images.githubusercontent.com/39853992/233248595-ec40d9f7-e9c0-4aa2-bd09-ef8389e7ec11.png)
Dataset Link:
- https://market.oceanprotocol.com/asset/did:op:d1831e870809147e7ec2aad2b679cccea541aa4b5577aa43c85c2da0392118a9

`publisherMarketFeeToken` (Goerli USDC address): 
- https://goerli.etherscan.io/token/0x07865c6E87B9F70255377e024ace6630C1Eaa37F 

**Desktop (please complete the following information):**
 - Mac OS
 - Brave v1.49.120

**Additional context**
- I am suspecting this is a decimal value issue somewhere around the subgraph else the contract where the implementation only support `18` decimal ERC20 address.

**Comment by jamiehewitt15** [comment]
Thanks for raising this @krisliew @soonhuat I'll take a look into it

**Comment by jamiehewitt15** [comment]
Hi @krisliew, thanks again for raising this issue. We have a potential fix (https://github.com/oceanprotocol/ocean-subgraph/pull/670) deployed on goerli. Could you test it out to see if it works with your flow?

**Comment by krisliew** [comment]
Hi @jamiehewitt15 I just retested the flow above on goerli, don't seems to be working.
![image](https://github.com/oceanprotocol/ocean-subgraph/assets/39853992/0110de7d-accd-4ab4-b182-e42a07ec3d91)

My dataset: https://market.oceanprotocol.com/asset/did:op:cbe80d9a0a28c2dd97581dfedaa59bf041ff281f440d72b8dbc1bfef5199a7a0

**Comment by jamiehewitt15** [comment]
> Hi @jamiehewitt15 I just retested the flow above on goerli, don't seems to be working.

Thank you for letting me know, I'm looking into it

**Comment by alexcos20** [comment]
are you using custom contracts? looking at datatoken (https://goerli.etherscan.io/address/0x3e349ef8ce5fbe614e580b1b702378a6e37cefcf#code), I cannot see the code, because contract is not verified

**Comment by jamiehewitt15** [comment]
Hi @krisliew, after spending some time looking into a potential cause for this in the subgraph, it turns out there was a bug in ocean.js where we were sending the wrong fee amount to the smart contract. 

I have written a fix for that here: https://github.com/oceanprotocol/ocean.js/pull/1748
