### ISSUE TITLE
Improve tests 

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-subgraph#665]
**Describe the bug**
Solve suggestions from #630 

- assert specific `eventIndex`. 
- put only necessary sleeps.

**Comment by mariacarmina** [comment]
UPDATE: Event index for `TokenCreated` & `NFTCreated` events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests.

E.g.: Subgraph query for a certain token's event index was 8 and in the actual tx event was 6.

**Comment by alexcos20** [comment]
create another issue pls for "UPDATE: Event index for TokenCreated & NFTCreated events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests"

**Comment by mihaisc** [comment]
@alexcos20 @mariacarmina status on this? can we close?

**Comment by mariacarmina** [comment]
No, we cannot close this, it's still valid.

**Comment by AnaLoznianu** [comment]
Duplicate of #676
