### ISSUE TITLE
Upgrade Rust & IPFS

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-subgraph#67]
Mar 30 01:41:34.664 INFO Trying IPFS node at: http://ipfs-cluster.dev.svc.cluster.local:5001/
thread 'tokio-runtime-worker' panicked at 'Failed to connect to IPFS: api returned unknwon error '405 - Method Not Allowed
'', node/src/main.rs:653:25

It seems that you are using a very old rust library
ipfs-api = { version = "=0.7.1", features = ["hyper-tls"] }

https://github.com/oceanprotocol/graph-node/blob/448ad2858c69e25eec622deaaa0d1c9c2305e13f/node/Cargo.toml#L22

The API version is now only supporting POST method, whilee GET is no longer supported.

Most likely due to your IPFS node version on image: ipfs/go-ipfs:v0.4.23, while ours are running on v0.7.0.

Any chance to upgrade the IPFS node version?

**Comment by md00ux** [comment]
I will test how graph-node works with latest IPFS image ( ipfs/go-ipfs:master-latest ) to identify the issues and possible workarounds.

**Comment by alexcos20** [comment]
@md00ux - any news?

**Comment by md00ux** [comment]
@alexcos20 , 

I tested with ` ipfs/go-ipfs:master-latest ` and `oceanprotocol/graph-node:latest`, there are no issues.
The subgraph was successfully deployed. 

In case IPFS 0.7.x has some issues, then one option is to upgrade to current version (actual 0.9.x). .

![image.png](https://images.zenhubusercontent.com/5fb238345472cf678a0e6ccc/2234dafd-4100-4c8c-9803-82e235a29f66)

![image.png](https://images.zenhubusercontent.com/5fb238345472cf678a0e6ccc/aad72fef-c4c5-4c59-81d0-258b2a2ba365)
