### ISSUE TITLE
Event index for `TokenCreated` & `NFTCreated` events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests.

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean-subgraph#677]
UPDATE: Event index for `TokenCreated` & `NFTCreated` events are overriden in the handlers. This was discovered while trying to assert the event indexes in the tests.

E.g.: Subgraph query for a certain token's event index was 8 and in the actual tx event was 6.

_Originally posted by @mariacarmina in https://github.com/oceanprotocol/ocean-subgraph/issues/665#issuecomment-1531524920_

**Comment by jamiehewitt15** [comment]
Has anything been done about this?
