### ISSUE TITLE
add compute jobs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ocean-subgraph#68]
On the `market`, https://github.com/oceanprotocol/market/issues/338 states that we should get the compute history from The Graph. But we can't rely on existing `tokenOrders` for that, see https://github.com/oceanprotocol/market/pull/462#issuecomment-811764879

So if we want to replace the expensive `provider` calls when doing `ocean.compute.status` we would need a way to get all compute jobs for a given account from the subgraph.

But if I got this right, starting a compute job in itself does not create an on-chain transaction, but only asks user for a signature. So this might make https://github.com/oceanprotocol/market/issues/338 not feasible altogether.

**Comment by mihaisc** [comment]
This can't be done. I'll comment on the issue the solution
