### ISSUE TITLE
[PDR][Lake] Enhance predictPayouts with Contract Address Array Filter

### ISSUE THREAD

**Issue by kdetry** [oceanprotocol/ocean-subgraph#767]
### Motivation
We're currently facing a challenge with the `predictPayouts` query in our project. The issue is that we can't filter results based on contract addresses directly. We're using the `prediction_contains` field, but it doesn't support lists of addresses. This limitation is making our data querying less efficient, especially when dealing with multiple contracts. (We create an "or" query for each contract address)

We need to introduce a new filter for contract addresses to improve our querying process.

### Proposed Solution: Contract Address Filter
The idea is to add a new filter in the `predictPayouts` query that allows us to input an array of contract addresses. This will enable us to fetch data for multiple contracts in a single query, making the process much more efficient.

Here’s an example of how the updated query might look:

```graphql
predictPayouts (
  first: 1000
  skip: 1000
  where: {
      {
        timestamp_gte: 1672531200,
        timestamp_lte: 1704153600,
        contract_in: ["0x18f54cc21b7a2fdd011bea06bba7801b280e3151", "0x2d8e2267779d27c2b3ed5408408ff15d9f3a3152"]
      }
  }
)
```

### Benefits of Adding This Filter
- **Improved Efficiency**: Allows querying multiple contracts simultaneously, saving time.
- **Enhanced Functionality**: Adds flexibility and precision to our data queries.

### DoD:
- [ ] Implement the `contract_in` filter in the `predictPayouts` query.
- [ ] it accepts multiple contract addresses as an array

**Comment by alexcos20** [comment]
this cannot be achieved, it would require to fork and change a lot on graphnode
