### ISSUE TITLE
Not working properly on moonbeam alpha

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#94]
There are no token orders [link](https://subgraph.moonbeamalpha.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20%20tokenOrders%7B%0A%20%20%20%20id%0A%20%20%20%20datatokenId%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20amount%0A%20%20%7D%0A%20%20%7D)
[Pool transactions](https://subgraph.moonbeamalpha.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20%20poolTransactions%7B%0A%20%20%20%20id%0A%20%20%0A%20%20%7D%0A%20%20%7D) are not in sync as well
And it seems it's not actually in sync

![image](https://user-images.githubusercontent.com/26000280/115730684-316fe680-a38f-11eb-9715-7fde318b7918.png)

**Comment by alexcos20** [comment]
is it still the case?  @jamiehewitt15 @mihaisc ?

**Comment by mihaisc** [comment]
Looks ok
